import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Layers3, Target, CalendarDays, Sun, HeartHandshake, Check } from 'lucide-react'
import { useLifeOS } from '../app/LifeOSProvider'
import { Button } from '../components/ui'
import { PageHeading } from '../components/PageHeading'
export default function GuidePage(){
 const {settings,habits,habitLogs,scheduleItems}=useLifeOS();const [step,setStep]=useState(0)
 const steps=[{title:'Dê lugar a cada assunto',label:'Áreas',icon:Layers3,text:'Casa, estudos, projetos ou uma categoria sua. Escolha só o que faz parte da sua rotina.',example:'Idiomas → praticar, estudar, escolher um curso.',to:'/categories',action:'Escolher minhas áreas',done:!!settings.enabledModules.length||!!settings.customCategories?.length},{title:'Escolha o que se repete',label:'Hábitos',icon:Target,text:'Dê nome a uma ação e escolha os dias. A opção reduzida é uma versão menor para os dias mais difíceis.',example:'Ler um livro → em um dia difícil, ler uma página.',to:'/habits',action:'Abrir meus hábitos',done:!!habits.length},{title:'Reserve um horário',label:'Agenda',icon:CalendarDays,text:'Um compromisso tem hora para começar. Use a agenda para reservar espaço, sem confundir horário com atividade concluída.',example:'Consulta na quinta, às 14h. Estudo às 19h.',to:'/settings?tab=schedule',action:'Organizar horários',done:!!scheduleItems.length},{title:'Conte como foi hoje',label:'Meu dia',icon:Sun,text:'Marque o que realizou e registre como se sente. Sono e água têm seus próprios registros.',example:'Feito, parcial ou ainda pendente. Você pode corrigir depois.',to:'/today',action:'Registrar meu dia',done:!!habitLogs.length},{title:'Leve os registros à terapia',label:'Acompanhamento',icon:HeartHandshake,text:'Escolha o que sua terapeuta pode ver e envie um link de leitura. Você pode encerrar esse acesso quando quiser.',example:'Sem conexão, registre normalmente. O envio retoma com o app aberto e conectado.',to:'/sharing',action:'Preparar compartilhamento',done:false}]
 const current=steps[step],Icon=current.icon
 return <div className="page calm-page guide-calm"><PageHeading eyebrow="Seu guia" title="Um passo de cada vez" description="Escolha uma etapa. Volte sempre que precisar."/><nav className="guide-stepper" aria-label="Etapas do guia">{steps.map((s,i)=><button key={s.label} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><span>{s.done?<Check size={17}/>:i+1}</span><strong>{s.label}</strong></button>)}</nav><section className="guide-single"><div className="guide-illustration"><Icon size={92} strokeWidth={1.2}/><span>{String(step+1).padStart(2,'0')}</span></div><div><span className="eyebrow">Etapa {step+1} de {steps.length}</span><h2>{current.title}</h2><p>{current.text}</p><div className="guide-example">{current.example}</div><Link className="button button--primary" to={current.to}>{current.action}<ArrowRight size={17}/></Link></div></section><footer className="guide-controls"><Button variant="ghost" disabled={!step} onClick={()=>setStep(step-1)}><ArrowLeft size={17}/>Anterior</Button><span>{step+1} / {steps.length}</span><Button variant="secondary" disabled={step===steps.length-1} onClick={()=>setStep(step+1)}>Próxima<ArrowRight size={17}/></Button></footer></div>
}
